export const signupContents = [
  {
    id: 1,
    title: "· 이메일*",
    type: "email",
    name: "email",
    placeholder: "이메일",
    btnText: "인증",
    gridTemplateAreas: `"elSpan elInput elBtn"`,
    gridTemplateAreasMobile: `"elSpan ." "elInput elBtn"`,
  },
  {
    id: 2,
    title: "인증번호를 받지 못하셨나요?",
    titleTwo: "재전송",
    name: "resend",
    gridTemplateAreas: `". elSpan elSpan"`,
    gridTemplateAreasMobile: `". ." "elSpan elSpan"`,
  },
  {
    id: 3,
    title: "· 인증번호 확인*",
    type: "text",
    name: "emailValidation",
    placeholder: "제한시간 10분",
    btnText: "확인",
    gridTemplateAreas: `"elSpan elInput elBtn"`,
    gridTemplateAreasMobile: `"elSpan ." "elInput elBtn"`,
  },
  {
    id: 4,
    title: "· 닉네임*",
    type: "text",
    name: "nickname",
    placeholder: "2~10자, 공백 없이 한글, 영문, 숫자",
    btnText: "중복 확인",
    gridTemplateAreas: `"elSpan elInput elBtn"`,
    gridTemplateAreasMobile: `"elSpan ." "elInput elBtn"`,
  },
  {
    id: 5,
    title: "· 비밀번호*",
    type: "password",
    name: "password",
    placeholder: "8자 이상 영어, 숫자, 특수문자 포함",
    btnText: "",
    gridTemplateAreas: `"elSpan elInput ."`,
    gridTemplateAreasMobile: `"elSpan ." "elInput ."`,
  },
  {
    id: 6,
    title: "· 비밀번호 확인*",
    type: "password",
    name: "passwordCheck",
    placeholder: "비밀번호 확인",
    btnText: "",
    gridTemplateAreas: `"elSpan elInput ."`,
    gridTemplateAreasMobile: `"elSpan ." "elInput ."`,
  },
  {
    id: 7,
    name: "passAlert",
    gridTemplateAreas: `". elSpan elSpan"`,
    gridTemplateAreasMobile: `". ." "elSpan elSpan"`,
  },
  {
    id: 8,
    title: "· 주소",
    type: "text",
    name: "address",
    required: "",
    placeholder: "선택사항",
    btnText: "주소 찾기",
    gridTemplateAreas: `"elSpan elInput elBtn"`,
    gridTemplateAreasMobile: `"elSpan ." "elInput elBtn"`,
  },
  {
    id: 9,
    title: "*주변지역 정보 제공을 위해 대략적인 주소를 입력받습니다.",
    name: "addressNotice",
    gridTemplateAreas: `". elSpan elSpan"`,
    gridTemplateAreasMobile: `". ." "elSpan elSpan"`,
  },
];
