export const signupContents = [
  {
    id: 1,
    title: "· 이메일*",
    type: "email",
    name: "email",
    required: "required",
    placeholder: "이메일",
    btnText: "인증",
    gridTemplateAreas: `"elSpan elInput elBtn ."`,
  },
  {
    id: 2,
    title: "인증번호를 받지 못하셨나요? 재전송",
    type: "text",
    name: "resend",
    required: "",
    placeholder: "",
    btnText: "",
    gridTemplateAreas: `". elSpan elSpan elSpan"`,
  },
  {
    id: 3,
    title: "· 인증번호 확인*",
    type: "number",
    name: "auth",
    required: "",
    placeholder: "제한시간 10분",
    btnText: "확인",
    gridTemplateAreas: `"elSpan elInput elBtn ."`,
  },
  {
    id: 4,
    title: "· 닉네임*",
    type: "text",
    name: "nickname",
    required: "required",
    placeholder: "2~10자, 공백 없이 한글, 영문, 숫자",
    btnText: "중복 확인",
    gridTemplateAreas: `"elSpan elInput elBtn elBtn"`,
  },
  {
    id: 5,
    title: "· 비밀번호*",
    type: "password",
    name: "password",
    required: "required",
    placeholder: "8자 이상 영어, 숫자, 특수문자 포함",
    btnText: "",
    gridTemplateAreas: `"elSpan elInput . ."`,
  },
  {
    id: 6,
    title: "· 비밀번호 확인*",
    type: "password",
    name: "",
    required: "",
    placeholder: "비밀번호 확인",
    btnText: "",
    gridTemplateAreas: `"elSpan elInput . ."`,
  },
  {
    id: 7,
    title: "· 주소",
    type: "text",
    name: "address",
    required: "",
    placeholder: "주소",
    btnText: "주소 찾기",
    gridTemplateAreas: `"elSpan elInput elBtn elBtn"`,
  },
  {
    id: 8,
    title: "", //상세주소
    type: "text",
    name: "addressDetail",
    required: "",
    placeholder: "상세주소 입력 (선택사항)",
    btnText: "",
    gridTemplateAreas: `"elSpan elInput elInput elInput"`,
  },
];
