name: CD

on:
  push:
    main: ["main"]
  # push:
  #   branches: ["develop"]
  # pull_request:
  #   branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3 #workflow에서 액세스할 수 있도록 저장소를 체크아웃

      # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File
        run: |
          echo "REACT_APP_BACKAPI=$REACT_APP_BACKAPI" >> .env
          echo "REACT_APP_CLIENT_ID=$REACT_APP_CLIENT_ID" >> .env
          echo "REACT_APP_REDIRECT_URI=$REACT_APP_REDIRECT_URI" >> .env
          echo "REACT_APP_KAKAO_MAP_KEY=$REACT_APP_KAKAO_MAP_KEY" >> .env
          echo "REACT_APP_BUCKET=$REACT_APP_BUCKET" >> .env
          echo "REACT_APP_REGION=$REACT_APP_REGION" >> .env
          echo "REACT_APP_ASSESSKEY_ID=$REACT_APP_ASSESSKEY_ID" >> .env
          echo "REACT_APP_SECRET_ACCESSKEY=$REACT_APP_SECRET_ACCESSKEY" >> .env
          echo "REACT_APP_SOCKET_URL=$REACT_APP_SOCKET_URL" >> .env
        env:
          REACT_APP_BACKAPI: ${{ secrets.REACT_APP_BACKAPI }}
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
          REACT_APP_KAKAO_MAP_KEY: ${{ secrets.REACT_APP_KAKAO_MAP_KEY }}
          REACT_APP_BUCKET: ${{ secrets.REACT_APP_BUCKET }}
          REACT_APP_REGION: ${{ secrets.REACT_APP_REGION }}
          REACT_APP_ASSESSKEY_ID: ${{ secrets.REACT_APP_ASSESSKEY_ID }}
          REACT_APP_SECRET_ACCESSKEY: ${{ secrets.REACT_APP_SECRET_ACCESSKEY }}
          REACT_APP_SOCKET_URL: ${{ secrets.REACT_APP_SOCKET_URL }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: S3 Deploy
        run: aws s3 sync ./build s3://buycation.co.kr/ --acl bucket-owner-full-control # 현재 build된 폴더에 접근 후 s3 버킷인 buycation.co.kr에 파일 업로드
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront Cache # 새로 리소스를 업데이트할 때 기존 캐시 무효화
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
          PATHS: "/index.html"
        continue-on-error: true
